### PR TITLE
Update Bootstrap & Use Bootstrap icon

### PR DESCRIPTION
**Pull request by pklion**
Update Bootstrap to version 5.

### CODE REVIEW

**Comment by chingucoding** [comment]
@5E7EN If we plan to remove bootstrap from the site, I think this PR would make it more difficult since we increase our dependencies on Bootstrap, so it might be better to hold off on this PR if we want to pursuit with removing bootstrap.

**Comment by 5E7EN** [comment]
> @5E7EN If we plan to remove bootstrap from the site, I think this PR would make it more difficult since we increase our dependencies on Bootstrap, so it might be better to hold off on this PR if we want to pursuit with removing bootstrap.

This PR doesn't really change much of what's already there. It's mostly just some renaming and similar.
If there was already an open PR presenting a non-bootstrap alternative then I'd reconsider merging this one, but until then, it just seems too harmless not to merge.

Perhaps you've got your own thoughts, @yaichenbaum?

**Comment by yaichenbaum** [comment]
@5E7EN I agree that unless someone is already planning to work on removing bootstrap then this PR can be merged.

**Comment by 5E7EN** [comment]
It doesn't seem to be in actively development as of yet, so I'll merge.

**Review by 5E7EN — APPROVED** [review]

**Pull request merged**
