### PR TITLE
Update profile config sample to include generic Powershell Core instead of fixed version

### PR DESCRIPTION
**Pull request by tasty0tomato**
Now PWSH7 is under development, but there may be 8, 9 and so on, and maybe we can delete the number.
## Description

delete the number 6.

### CODE REVIEW

**Review by chingucoding — APPROVED** [review]

**Comment by chingucoding** [comment]
@yaichenbaum Seems reasonable to me, what do you think?

**Comment by yaichenbaum** [comment]
@tasty0tomato Have you tested that the profile works properly?

**Comment by tasty0tomato** [comment]
> @tasty0tomato Have you tested that the profile works properly?

Maybe yes, I mean this is what I do in my _Files_

**Comment by yaichenbaum** [comment]
Sounds good! LGTM

**Review by yaichenbaum — APPROVED** [review]

**Pull request merged**
