### PR TITLE
Update icons

### PR DESCRIPTION
**Pull request by DeveloperWOW64**
## Description
These changes update the icons from the old version of Files to the newer one.

## How Has This Been Tested?
Tested by running GH pages on my repo (https://developerwow64.github.io/files-community.github.io

Note: The favicon is really small, and even if I use the dimensions of the old favicon it still looks small. can anyone provide me with the correct image?

### CODE REVIEW

**Review by chingucoding — CHANGES_REQUESTED** [review]
Thanks for updating the icons! However, the favicon being shown on the tab is now quite small:

Screenshot of new and old icon on Edge Tabs showing size difference

**Comment by DeveloperWOW64** [comment]
I can't get the dimensions right.

**Comment by chingucoding** [comment]
I think the problem is that there is a lot of padding around the actual Files icon and the tabs also render that whitespace around it, thus creating an icon that is tiny.

**Comment by DeveloperWOW64** [comment]
ok. I have an idea. What if I crop the image?

**Comment by chingucoding** [comment]
That should probably work.

**Comment by DeveloperWOW64** [comment]
Fixed!

**Comment by DeveloperWOW64** [comment]
(https://developerwow64.githun.io/files-community.github.io

**Review by chingucoding — APPROVED** [review]
Awesome, looks good to me!

**Pull request merged**
