### PR TITLE
Added new items to Features section, added header image and navbar

### PR DESCRIPTION
**Pull request by lukakopajtic**
There are now a total of 6 features that are present in Files 1.0, i also added a image of Files window to the header. A navbar has been added for easier access to Discord, in the future links can be placed inside for easier navigation.

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@lukakopajtic Can you share a screenshot of the changes?

**Comment by lukakopajtic** [comment]
> @lukakopajtic Can you share a screenshot of the changes?

image

Here's the before and after. On the right, you can see new navbar where links can be added in the future. I added three new items to the features and changed the wording a bit. In the next commit i would just place the Files icon right next to the "Files" title, right now it just floats on the left side.

**Comment by yaichenbaum** [comment]
I would like to hold off on this as Michael West was working on a nav bar. Let me see if they can comment here 😃.

**Comment by itsmichaelwest** [comment]
This looks good, and I think having the GitHub and Discord links at the top is the right move. I'd perhaps like to see a bit more contrast on those links, they are quite washed out and might be hard to see -- adjusting `#navigation #social-media a`'s background and hover background.

The inclusion of a more prominent screenshot is great too (even if not related to the navbar)! Not sure about having it fade out, bit that's beyond the scope of the comment requested from me. 🙂

**Comment by lukakopajtic** [comment]
Regarding the GitHub and Discord links in the navbar, the icons would be even more visible without the circles, but then we just need to change them in the footer as well so they match. 

And like @itsmichaelwest said, we could use the flat, unfaded screenshot for a more professional look, but then the elements need to be tweaked a bit. No bottom margins on the header and some kind of shadow or divider would have to be introduced, because without it the screenshot and "features section blend in together.

**Comment by Ein-Tim** [comment]
Was to open a Issue for this but maybe this PR could also update the ©2020 at the very bottom to ©2021? 😀

**Comment by 5E7EN** [comment]
I've been told there are still changes being made on this PR. If you can confirm this is correct, @lukakopajtic, I'll hold off on the review for now until those changes are complete - otherwise, we can continue getting this merged.

**Comment by lukakopajtic** [comment]
@5E7EN i am not making any changes at the moment, there was some discussion on Discord about a different header image, so i paused. But we could still merge and change the image afterwards.

**Comment by dawgdemi** [comment]
> There are now a total of 6 features that are present in Files 1.0, i also added a image of Files window to the header. A navbar has been added for easier access to Discord, in the future links can be placed inside for easier navigation.

**Comment by chingucoding** [comment]
@lukakopajtic Do you want to continue working on this PR? There are merge conflicts that would need fixing and #50 will introduce even more.

**Comment by chingucoding** [comment]
Closing due to unresolved merge conflicts. Please reopen this PR if you wish to continuing with this PR @lukakopajtic :)

**Pull request closed without merging**
